version: "3.7"

services:
  app:
    build:
      context: ./Docker/php/8.0
    container_name: saude_ti_test_app
    image: somosyampi/php:8.0
    init: true
    volumes:
        - .:/app:delegated
    networks:
        - saude_ti

  nginx:
    build:
      context: ./Docker/nginx
    image: somosyampi/http
    ports:
        - 8000:80
    volumes:
        - .:/app:delegated
    environment:
      FPM_HOST: app
    networks:
        - saude_ti
    depends_on:
        - app

  db:
    image: mariadb:10.2
    container_name: saude_ti_test_db
    volumes:
        - ./mysql/data:/var/lib/mysql:${VOLUME_ATR:-delegated}
    restart: always
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: db_saude_ti
    networks:
        - saude_ti

networks:
  saude_ti:
    name: saude_ti
